// Сгенерировано из philosophy_graph.html — правки вносить сюда, не в исходник.

import './modules/boot-defs.js';
import './modules/core/base-cells.js';
import './modules/core/events.js';
import './modules/core/graph-index.js';
import './modules/core/link-facts.js';
import './modules/core/long-task.js';
import './modules/core/relation-types.js';
import './modules/core/search.js';
import './modules/core/session.js';
import './modules/core/time.js';
import './modules/core/visibility.js';
import './modules/data/mutate.js';
import './modules/data/save.js';
import './modules/dead.js';
import './modules/filters/beyond-filter.js';
import './modules/filters/chains.js';
import './modules/filters/filters.js';
import './modules/graph/click-actions.js';
import './modules/graph/graph-data.js';
import './modules/graph/graph-selection.js';
import './modules/metrics/by-link-type.js';
import './modules/metrics/concept-dynamics.js';
import './modules/metrics/descriptions.js';
import './modules/metrics/format.js';
import './modules/metrics/generativity.js';
import './modules/metrics/graph-cache.js';
import './modules/metrics/link-indexes.js';
import './modules/metrics/network.js';
import './modules/metrics/philosopher.js';
import './modules/metrics/philosophical.js';
import './modules/metrics/rankings.js';
import './modules/metrics/scope-reset.js';
import './modules/metrics/scope-select.js';
import './modules/metrics/scope.js';
import './modules/metrics/similarity-concepts.js';
import './modules/metrics/similarity-philosophers.js';
import './modules/metrics/tension-cache.js';
import './modules/metrics/tradition-bridging.js';
import './modules/modal/assembly.js';
import './modules/modal/auth.js';
import './modules/modal/concept-view.js';
import './modules/modal/connection-edit.js';
import './modules/modal/connection-view.js';
import './modules/modal/context.js';
import './modules/modal/core.js';
import './modules/modal/descriptions.js';
import './modules/modal/dirty.js';
import './modules/modal/edit-forms.js';
import './modules/modal/edit-rights.js';
import './modules/modal/entry.js';
import './modules/modal/integrity.js';
import './modules/modal/persist.js';
import './modules/modal/philosopher-view.js';
import './modules/modal/profile-concept.js';
import './modules/modal/profile-philosopher.js';
import './modules/modal/search.js';
import './modules/paths/analysis.js';
import './modules/paths/chronology.js';
import './modules/paths/path-descriptions.js';
import './modules/paths/path-ui.js';
import './modules/paths/shortest-path.js';
import './modules/render/canvas-core.js';
import './modules/render/d3-layer.js';
import './modules/render/draw-link.js';
import './modules/render/geometry.js';
import './modules/render/grouping.js';
import './modules/render/interactions.js';
import './modules/render/loop.js';
import './modules/render/metric-visualization.js';
import './modules/render/picking.js';
import './modules/render/render-state.js';
import './modules/render/scene.js';
import './modules/render/selection.js';
import './modules/render/similarity-overlay.js';
import './modules/render/simulation.js';
import './modules/render/tooltip-el.js';
import './modules/state/edit.js';
import './modules/state/filters.js';
import './modules/state/metrics-scope.js';
import './modules/state/paths.js';
import './modules/state/render.js';
import './modules/state/stats.js';
import './modules/stats/coverage.js';
import './modules/stats/modal.js';
import './modules/stats/results.js';
import './modules/stats/run.js';
import './modules/stats/views/advanced.js';
import './modules/stats/views/comparison.js';
import './modules/stats/views/network.js';
import './modules/stats/views/philosopher.js';
import './modules/stats/views/philosophical.js';
import './modules/stats/views/rankings.js';
import './modules/ui/about.js';
import './modules/ui/export.js';
import './modules/ui/hint.js';
import './modules/ui/legend.js';
import './modules/ui/panels.js';
import './modules/ui/search-legend.js';
import './modules/ui/search-link.js';
import './modules/ui/search-philosopher.js';
import './modules/util/color.js';
import './modules/util/html.js';
import './modules/util/philosopher-label.js';
import './modules/util/ru.js';
import './modules/widgets/custom-select.js';

import './modules/ui/actions-byname.js';
import './modules/ui/actions-static.js';
import { installDelegation } from './modules/ui/delegation.js';
import './modules/ui/actions-dyn.js';
import { boot } from './boot.js';

installDelegation();      // делегирование: разметка несёт имя действия
boot().catch(err => {
  console.error('запуск не удался:', err);
  const el = document.getElementById('filterStats');
  if (el) el.textContent = 'Ошибка запуска: ' + err.message;
});
